# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy only the necessary files to optimize build
COPY . /app

# Ensure the images folder exists in the container
COPY ./images /app/images

# Install dependencies
RUN pip install --no-cache-dir streamlit requests

# Expose the port for Streamlit
EXPOSE 8501

# Command to run Streamlit
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
